FROM nginx:1.19.7-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /var/wwww/html -p touch /var/www/html/index.html

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx","-g", "daemon off;" ]